baseURL: http://example.org/
languageCode: ja-jp
title: My New Site
theme: hugo-newcss-theme
copyright: "&copy; 2022 yourname"

menu:
  header:
    - name: Home
      weight: 1
      url: /

    - name: Posts
      weight: 2
      url: /posts

    - name: Tags
      weight: 3
      url: /tags

    - name: MyGithub
      weight: 4
      url: https://github.com/
      params:
        newtab: true

params:
  showsource: true
  contenturl: https://github.com/yourname/site-repo/tree/master/content/
  description: Hello
  image: #ogp image

markup:
  highlight:
    style: monokai #see https://xyproto.github.io/splash/docs/all.html
